application: link-to-health
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: script.app

libraries:
- name: webapp2
  version: latest
